# Generated by Django 3.2.12 on 2022-05-21 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DATA_ALL_SEANSES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_key', models.CharField(default='lrgfwyNuQWGqnPx', max_length=20, verbose_name='Специальный код сеанса')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/seans', verbose_name='Фото')),
                ('name', models.CharField(max_length=50, verbose_name='Имя сеанса')),
                ('discription', models.CharField(max_length=190, verbose_name='Описание сеанса')),
                ('categori', models.CharField(max_length=5, verbose_name='Возрастное ограничение (6,12,18)')),
                ('summa', models.IntegerField(default=1115, verbose_name='Цена билета')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('class_seans', models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концерная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино']], default=3)),
            ],
            options={
                'verbose_name': 'Сеанс_афишы',
                'verbose_name_plural': 'Сеансы_афиши',
            },
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Никнейм пользователя')),
                ('password', models.CharField(max_length=41, verbose_name='Пароль пользователя')),
                ('isGreen', models.BooleanField(verbose_name='Показатель если пользоветель по лицу то true')),
                ('info_vac', models.CharField(blank=True, max_length=50, verbose_name='ИНФО о вакцинации формат дата')),
                ('sopose', models.CharField(max_length=5, verbose_name='Qr, 18, med')),
                ('email', models.EmailField(max_length=30, verbose_name='Email пользователя')),
                ('list_frends', models.TextField(blank=True, verbose_name='Все друзья пользователя')),
                ('loock_like', models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концерная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино']], default=3)),
            ],
            options={
                'verbose_name': 'Пользователь_информация',
                'verbose_name_plural': 'Пользователи_информация',
            },
        ),
        migrations.CreateModel(
            name='SEANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seanses', models.TextField(blank=True, verbose_name='Все сеансы пользоветеля')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user')),
            ],
            options={
                'verbose_name': 'Пользователь_сеанс',
                'verbose_name_plural': 'Пользователи_сеансы',
            },
        ),
        migrations.CreateModel(
            name='II',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_photo', models.CharField(blank=True, max_length=3000, verbose_name='Инфо лица')),
                ('now', models.TextField(blank=True, verbose_name='какие мероприятия сейчас у пользоваетля запланированны')),
                ('code', models.CharField(blank=True, max_length=12, verbose_name='Специальный код')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user')),
            ],
            options={
                'verbose_name': 'Пользователь_лицо',
                'verbose_name_plural': 'Пользователи_лица',
            },
        ),
    ]
