# Generated by Django 3.2.12 on 2022-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_auto_20220529_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isGreen',
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='dxltJKVzQUwTcPZ', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1296, verbose_name='Цена билета'),
        ),
    ]
