# Generated by Django 3.2.12 on 2022-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_auto_20220530_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='WwyNxTfGhrYmUdO', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=699, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='seans',
            name='seanses',
            field=models.TextField(blank=True, default=' ', verbose_name='Все сеансы пользоветеля'),
        ),
    ]
