# Generated by Django 3.2.12 on 2022-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_auto_20220530_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.TextField(blank=True, verbose_name='Лайкнутые категории'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='FzZXHdNOLMupeqj', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=216, verbose_name='Цена билета'),
        ),
    ]
