# Generated by Django 3.2.12 on 2022-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0011_auto_20220602_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ii',
            name='frends',
            field=models.ManyToManyField(related_name='friends', to='myapp2.USER'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='YRzMovSlaLniGUD', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=409, verbose_name='Цена билета'),
        ),
    ]
