# Generated by Django 3.2.12 on 2022-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0012_auto_20220603_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='list_frends',
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='pWSCTLuiKyhewIX', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1281, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='ii',
            name='frends',
            field=models.ManyToManyField(default='', related_name='friends', to='myapp2.USER'),
        ),
    ]
