# Generated by Django 3.2.12 on 2022-06-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0013_auto_20220603_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ii',
            name='frends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_myapp2_user_friends_+', to='myapp2.USER'),
        ),
        migrations.AddField(
            model_name='user',
            name='list_frends',
            field=models.TextField(blank=True, verbose_name='Заявки на принятия в друзья пользователя'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='xHUyujRrvLfCDqP', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=370, verbose_name='Цена билета'),
        ),
    ]
