# Generated by Django 3.2.12 on 2022-06-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0018_auto_20220603_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='ioxEfDcdLQhmluZ', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=394, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user'),
        ),
    ]
