# Generated by Django 3.2.12 on 2022-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0034_auto_20220603_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_all_seanses',
            name='isPush',
            field=models.BooleanField(default=False, verbose_name='По пушкинской можно оплатить'),
        ),
        migrations.AddField(
            model_name='data_all_seanses',
            name='mesto',
            field=models.CharField(default='', max_length=50, verbose_name='Место проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='ydZpJGPBwnAhuRm', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=973, verbose_name='Цена билета'),
        ),
    ]
