# Generated by Django 3.2.12 on 2022-06-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0036_auto_20220603_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='my_friends',
            field=models.ManyToManyField(blank=True, related_name='_myapp2_user_my_friends_+', to='myapp2.USER'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='wmWyvufgtjbMDHT', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=818, verbose_name='Цена билета'),
        ),
    ]
