# Generated by Django 3.2.12 on 2022-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0037_auto_20220603_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_friends',
        ),
        migrations.AddField(
            model_name='user',
            name='list_req_frends',
            field=models.TextField(blank=True, verbose_name='Заявки на принятия в друзья пользователя'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='PyteCESWqkpZmgi', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1443, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_frends',
            field=models.TextField(blank=True, verbose_name='Все друзья пользователя'),
        ),
    ]
