# Generated by Django 3.2.12 on 2022-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0038_auto_20220603_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ico',
            field=models.ImageField(default='no_photo.png', upload_to='img_user/'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='GZdxJEreCoFaNRL', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=529, verbose_name='Цена билета'),
        ),
    ]
