# Generated by Django 3.2.12 on 2022-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0039_auto_20220606_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='OKLyoCWaSsVpIBz', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1278, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ico',
            field=models.ImageField(default='img_user/no_photo.png', upload_to='img_user/'),
        ),
    ]
