# Generated by Django 4.0.2 on 2022-02-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Никнейм пользователя')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль пользователя')),
                ('isGreen', models.BooleanField(verbose_name='Показатель если пользоветель по лицу то true')),
                ('info_vac', models.CharField(max_length=50, verbose_name='ИНФО о вакцинации формат дата')),
                ('sopose', models.CharField(max_length=5, verbose_name='Qr, <18, med')),
                ('email', models.CharField(max_length=30, verbose_name='Email пользователя')),
                ('list_frends', models.TextField(verbose_name='Все друзья пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='SEANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seanses', models.TextField(verbose_name='Все сеансы пользоветеля')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='II',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_photo', models.CharField(max_length=150, verbose_name='Инфо лица')),
                ('now', models.TextField(verbose_name='какие мероприятия сейчас у пользоваетля запланированны')),
                ('code', models.CharField(max_length=10, verbose_name='Специальный код')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
