# Generated by Django 3.2.12 on 2022-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATA_ALL_SEANSES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_img', models.CharField(max_length=50, verbose_name='Ссылка на фото')),
                ('name', models.CharField(max_length=50, verbose_name='Имя сеанса')),
                ('discription', models.CharField(max_length=190, verbose_name='Описание сеанса')),
                ('categori', models.CharField(max_length=5, verbose_name='Возрастное ограничение (6,12,18)')),
            ],
            options={
                'verbose_name': 'Сеанс_афишы',
                'verbose_name_plural': 'Сеансы_афиши',
            },
        ),
        migrations.AlterModelOptions(
            name='ii',
            options={'verbose_name': 'Пользователь_лицо', 'verbose_name_plural': 'Пользователи_лица'},
        ),
        migrations.AlterModelOptions(
            name='seans',
            options={'verbose_name': 'Пользователь_сеанс', 'verbose_name_plural': 'Пользователи_сеансы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь_информация', 'verbose_name_plural': 'Пользователи_информация'},
        ),
        migrations.AlterField(
            model_name='ii',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Специальный код'),
        ),
        migrations.AlterField(
            model_name='ii',
            name='info_photo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Инфо лица'),
        ),
        migrations.AlterField(
            model_name='ii',
            name='now',
            field=models.TextField(blank=True, verbose_name='какие мероприятия сейчас у пользоваетля запланированны'),
        ),
        migrations.AlterField(
            model_name='seans',
            name='seanses',
            field=models.TextField(blank=True, verbose_name='Все сеансы пользоветеля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info_vac',
            field=models.CharField(blank=True, max_length=50, verbose_name='ИНФО о вакцинации формат дата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_frends',
            field=models.TextField(blank=True, verbose_name='Все друзья пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=41, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sopose',
            field=models.CharField(max_length=5, verbose_name='Qr, 18, med'),
        ),
    ]
