# Generated by Django 3.2.12 on 2022-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220223_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_all_seanses',
            name='src_img',
        ),
        migrations.AddField(
            model_name='data_all_seanses',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/seans', verbose_name='Фото'),
        ),
    ]
