# Generated by Django 3.2.12 on 2022-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220225_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='EJqrMySQoXPmhcG', max_length=50, verbose_name='Специальный код сеанса'),
        ),
    ]
