# Generated by Django 3.2.12 on 2022-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_data_all_seanses_ident_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=223, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='qvmGzLVlgCEDNoY', max_length=20, verbose_name='Специальный код сеанса'),
        ),
    ]
