# Generated by Django 3.2.12 on 2022-02-26 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220226_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_all_seanses',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='ghwGqFcbmoPvDAO', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=270, verbose_name='Цена билета'),
        ),
    ]
