# Generated by Django 3.2.12 on 2022-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220226_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='NDJyVdeRkgfpBLA', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1399, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='ii',
            name='info_photo',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Инфо лица'),
        ),
    ]
