# Generated by Django 3.2.12 on 2022-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220331_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='class_seans',
            field=models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концерная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино']], default=3),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='QSPlfYbazBoveOq', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=759, verbose_name='Цена билета'),
        ),
    ]
