# Generated by Django 3.2.12 on 2022-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220331_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='WBYCZKsUqbEwAzP', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=633, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='ii',
            name='code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Специальный код'),
        ),
    ]
